/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { default as l1Contracts } from "./deployedContractsL1";
import { default as l2Contracts } from "./deployedContractsL2";
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  ...l1Contracts,
  ...l2Contracts,
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
